#!/bin/sh -e

# ----------------------------------------------------------------------
# pan_p_cpp_do
# ----------------------------------------------------------------------

redo-ifchange pan.hpp
sed -e 's/this;/_this;/g' \
  -e 's/this *=/_this =/g' \
  -e 's/this)/_this)/g' \
  -e 's/o__this/o_this/g' \
  -e 's/pan\.h/pan.hpp/' < pan.p > $3
